name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: functions
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install node modules
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Type check
        run: npm run type
      - name: Create serviceAccountKey.json for online testing
        run: echo "$SERVICE_ACCOUNT_KEY_JSON" > ../serviceAccountKey.json
        env:
          SERVICE_ACCOUNT_KEY_JSON: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}
      - name: Tests
        run: npm run test:ci
        env:
          TEST_PROJECT_ID: ${{ secrets.TEST_PROJECT_ID }}
