name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: functions
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm ci
      - run: npm run lint
      - name: Type check
        uses: gozala/typescript-error-reporter-action@v1.0.5
        with:
          project: functions/tsconfig.json
      - name: Create serviceAccountKey.json for online testing
        run: echo "$SERVICE_ACCOUNT_KEY_JSON" > ../serviceAccountKey.json
        env:
          SERVICE_ACCOUNT_KEY_JSON: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}
      - run: npm run test:ci
        env:
          TEST_PROJECT_ID: ${{ secrets.TEST_PROJECT_ID }}
